# Generated by Django 2.2.5 on 2019-09-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_spoken_with',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Recent',
        ),
    ]
